import type { TaskWithRelations, Contact } from '@meeting-task-tool/shared';

/**
 * Convert tasks to CSV format
 */
export function exportTasksToCSV(tasks: TaskWithRelations[]): string {
    const headers = [
        'ID',
        'Description',
        'Status',
        'Priority',
        'Assignee',
        'Deadline',
        'Created At',
        'Meeting Title',
    ];

    const rows = tasks.map((task) => {
        return [
            task.id,
            `"${task.description.replace(/"/g, '""')}"`, // Escape quotes
            task.status,
            task.priority,
            task.assigneeName || task.assignee?.name || 'Unassigned',
            task.deadline ? new Date(task.deadline).toLocaleDateString() : '',
            new Date(task.createdAt).toLocaleDateString(),
            `"${(task.meeting?.title || '').replace(/"/g, '""')}"`,
        ].join(',');
    });

    return [headers.join(','), ...rows].join('\n');
}

/**
 * Generate a markdown weekly progress report
 */
export function generateWeeklyReport(
    tasks: TaskWithRelations[],
    startDate: Date,
    endDate: Date
): string {
    const completedTasks = tasks.filter((t) => {
        if (t.status !== 'completed') return false;
        const date = t.updatedAt ? new Date(t.updatedAt) : new Date(t.createdAt);
        return date >= startDate && date <= endDate;
    });

    const inProgressTasks = tasks.filter((t) => {
        if (t.status !== 'in_progress') return false;
        // Include all in-progress tasks regardless of date, as they are current
        return true;
    });

    const upcomingDeadlines = tasks.filter((t) => {
        if (!t.deadline || t.status === 'completed' || t.status === 'cancelled') return false;
        const deadline = new Date(t.deadline);
        const nextWeek = new Date(endDate.getTime() + 7 * 24 * 60 * 60 * 1000);
        return deadline >= endDate && deadline <= nextWeek;
    });

    const report = [
        `# Weekly Progress Report`,
        `**Period:** ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
        '',
        `## ✅ Completed Tasks (${completedTasks.length})`,
        completedTasks.length === 0
            ? '_No tasks completed this period._'
            : completedTasks
                .map(
                    (t) =>
                        `- **${t.description}** (Assignee: ${t.assigneeName || t.assignee?.name || 'Unassigned'
                        })`
                )
                .join('\n'),
        '',
        `## 🚧 In Progress (${inProgressTasks.length})`,
        inProgressTasks.length === 0
            ? '_No tasks currently in progress._'
            : inProgressTasks
                .map(
                    (t) =>
                        `- **${t.description}** - ${t.priority.toUpperCase()} Priority`
                )
                .join('\n'),
        '',
        `## 📅 Upcoming Deadlines (Next 7 Days)`,
        upcomingDeadlines.length === 0
            ? '_No immediate deadlines._'
            : upcomingDeadlines
                .map(
                    (t) =>
                        `- **${new Date(t.deadline!).toLocaleDateString()}**: ${t.description
                        } (${t.assigneeName || t.assignee?.name || 'Unassigned'})`
                )
                .join('\n'),
        '',
        '---',
        `*Generated by Meeting Task Tool on ${new Date().toLocaleString()}*`,
    ].join('\n');

    return report;
}

/**
 * Trigger a file download
 */
export function downloadFile(content: string, filename: string, type: string) {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
